Added the team structure and some debugging functionality for the client
jnormington/clubhouse-go pull request #4
Opened 2019-04-17 16:52 UTC by djthorpe

Added the methods "ListTeams" and "GetTeam" and also a simple test file. Also added a method for the client so you can switch debugging on.

2019-11-28 18:51 UTC, jnormington requested changes
hey @djthorpe 

I'm so sorry I got no notification and was just browsing the repos. Just one change and I'll merge.
However seeing as its been almost 7months I'll understand if you don't want to make the changes, if not I'll update with your say so and merge.

2019-11-28 18:51 UTC, jnormington commented on clubhouse.go
> +	}
Could this not be part of the if ch.Debug if statement above ?

2019-11-28 18:51 UTC, jnormington commented on team_test.go
> +	ch "github.com/djthorpe/clubhouse-go"
Import needs to updated

2019-11-28 18:51 UTC, jnormington commented on team_test.go
> +}
These I guess are more smoke tests :+1:

2019-12-10 21:47 UTC, djthorpe commented
Sorry I don'thave access to clubhouse anymore, so closing this pull request. Apologies.

2019-12-10 21:47 UTC, closed without merging